### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/ChimeraX-icon.svg'

### ISSUE THREAD

**Issue by rupesh-sinha** [RBVI/ChimeraX#27]
Hi,

I was trying to install [chimerax-rc.deb](https://www.rbvi.ucsf.edu/chimerax/cgi-bin/secure/chimerax-get.py?file=current/ubuntu-22.04/chimerax-rc.deb) on my ubuntu 22.04 system using following command but returned error:

(base) rupesh@rupesh-sinha:~/rupesh/colabfold$ sudo apt-get install /home/rupesh/Downloads/chimerax-rc.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'ucsf-chimerax' instead of '/home/rupesh/Downloads/chimerax-rc.deb'
ucsf-chimerax is already the newest version (1.5+rc2022.10.18ubuntu22.04).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up ucsf-chimerax (1.5+rc2022.10.18ubuntu22.04) ...
Install desktop menu and associated mime types
Traceback (most recent call last):
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/__main__.py", line 726, in init
    run(sess, cmd)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/commands/run.py", line 38, in run
    results = command.run(text, log=log, return_json=return_json)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/commands/cli.py", line 2897, in run
    result = ci.function(session, **kw_args)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/linux/cmd.py", line 23, in linux_xdg_install
    install(session, verbose=verbose, system=system)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/linux/_xdg.py", line 430, in install
    install_icons(session, info, verbose)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/linux/_xdg.py", line 288, in install_icons
    shutil.copyfile(path, os.path.join(p2, '%s.svg' % info.name))
  File "/usr/lib/ucsf-chimerax/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/ChimeraX-icon.svg'
dpkg: error processing package ucsf-chimerax (--configure):
 installed ucsf-chimerax package post-installation script subprocess returned error exit status 70
Errors were encountered while processing:
 ucsf-chimerax
E: Sub-process /usr/bin/dpkg returned an error code (1)

Please help!

Note: ChimeraX 1.4 was running fine in my system I thought to upgrade to 1.5 to use 'alphafold contacts' command.

**Comment by tomgoddard** [comment]
This issue is now reported in the main ChimeraX issue tracking system here

https://www.rbvi.ucsf.edu/trac/ChimeraX/ticket/7830

**Comment by rupesh-sinha** [comment]
Hi I tried again with the Oct 19th 2022 release but getting the similar error:

$ sudo apt-get install ~/Downloads/chimerax-rc.deb 
[sudo] password for rupesh: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'ucsf-chimerax' instead of '/home/rupesh/Downloads/chimerax-rc.deb'
The following packages will be upgraded:
  ucsf-chimerax
1 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.
1 not fully installed or removed.
Need to get 0 B/338 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /home/rupesh/Downloads/chimerax-rc.deb ucsf-chimerax amd64 1.5+rc2022.10.20ubuntu22.04 [338 MB]
(Reading database ... 241272 files and directories currently installed.)
Preparing to unpack .../Downloads/chimerax-rc.deb ...
Deregister desktop menu and associated mime types
Remove Python cache files
Unpacking ucsf-chimerax (1.5+rc2022.10.20ubuntu22.04) over (1.5+rc2022.10.18ubuntu22.04) ...
Setting up ucsf-chimerax (1.5+rc2022.10.20ubuntu22.04) ...
Install desktop menu and associated mime types
Traceback (most recent call last):
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/__main__.py", line 726, in init
    run(sess, cmd)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/commands/run.py", line 38, in run
    results = command.run(text, log=log, return_json=return_json)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/commands/cli.py", line 2897, in run
    result = ci.function(session, **kw_args)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/linux/cmd.py", line 23, in linux_xdg_install
    install(session, verbose=verbose, system=system)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/linux/_xdg.py", line 430, in install
    install_icons(session, info, verbose)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/linux/_xdg.py", line 288, in install_icons
    shutil.copyfile(path, os.path.join(p2, '%s.svg' % info.name))
  File "/usr/lib/ucsf-chimerax/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/ChimeraX-icon.svg'
dpkg: error processing package ucsf-chimerax (--configure):
 installed ucsf-chimerax package post-installation script subprocess returned error exit status 70
Processing triggers for man-db (2.10.2-1) ...
Errors were encountered while processing:
 ucsf-chimerax
N: Download is performed unsandboxed as root as file '/home/rupesh/Downloads/chimerax-rc.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)

Thanks in advance for your help!

**Comment by gregcouch** [comment]
This is fixed.  And is in the daily builds since October 21st.
